import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GameModel} from '../src/game/model.js';
import {LocalStore} from '../src/game/storage.js';
import {RULES,RULESET_VERSION,FIELD,POWERS,levelRules,mulberry32,wordCardWidth} from '../src/game/rules.js';
import {economyRules,createEconomy,prepareEconomy,restoreEconomy,nextSpellGap,validEconomy} from '../src/game/economy.js';
const run=(options={})=>{const m=new GameModel();m.start({seed:1147,...options});m.drainEvents();return m;};
const mem=()=>{const data=new Map();return {data,getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,String(v))};};
function draw(m,count){const out=[];for(let i=0;i<count;i++){m.words=[];assert.equal(m.spawn(),true);out.push({...m.words[0],ordinal:m.spawnedThisLevel});m.drainEvents();}return out;}
function finish(m){m.words=[];m.clearLevel();assert.equal(m.phase,'level-clear');}
const OLD_CURVE=[[1,36],[3,45],[6,58],[12,76],[24,99],[36,116],[48,132]];
function oldSpeed(n){for(let i=1;i<OLD_CURVE.length;i++)if(n<=OLD_CURVE[i][0]){const a=OLD_CURVE[i-1],b=OLD_CURVE[i];return a[1]+(b[1]-a[1])*(n-a[0])/(b[0]-a[0]);}}
const legacy=()=>{const m=run({level:5});const c=m.checkpoint();c.ruleset='typekeeper-3.2.0';delete c.economy;c.inventory={fire:3,ice:3,slow:1,wind:2};return c;};

test('v3.2.1 capacity is two per spell, eight in total; effect strength is preserved',()=>{assert.equal(RULES.inventoryCapacity,2);assert.equal(POWERS.length*RULES.inventoryCapacity,8);assert.equal(RULES.iceDuration,6);assert.equal(RULES.slowDuration,8);assert.equal(RULES.slowFactor,.42);});
for(const pace of ['relaxed','classic','maniac']){
 test(`${pace}: a new campaign has no books and only one chapter-one opportunity`,()=>{const m=run({pace});assert.deepEqual(Object.values(m.inventory),[0,0,0,0]);const d=draw(m,12),powers=d.filter(w=>POWERS.includes(w.kind));assert.deepEqual(powers.map(w=>[w.ordinal,w.kind]),[[6,'ice']]);assert.deepEqual(Object.values(m.inventory),[0,0,0,0]);});
 test(`${pace}: opening is 10–15% gentler, 4–6 is 5–10% gentler, then rejoins the curve`,()=>{const scale=levelRules(12,pace).speed/76;for(let n=1;n<=6;n++){const ratio=levelRules(n,pace).speed/scale/oldSpeed(n);assert.ok(ratio>=(n<=3?.85:.90)-1e-9&&ratio<=(n<=3?.90:.95)+1e-9);}assert.equal(levelRules(12,pace).speed,76*scale);assert.equal(levelRules(24,pace).speed,99*scale);assert.ok(Math.abs(levelRules(48,pace).speed/(132*scale)-1.03)<1e-9);});
 test(`${pace}: every chapter remains monotone with no opening or Endless difficulty reset`,()=>{for(let n=2;n<=250;n++){const a=levelRules(n-1,pace),b=levelRules(n,pace);assert.ok(b.speed>=a.speed&&b.speed/a.speed<1.17);assert.ok(b.interval<=a.interval);}});
}
for(const [level,min,max] of [[1,8,11],[4,8,11],[7,8,10],[11,8,10],[13,7,10],[23,7,10],[25,6,9],[47,6,9],[49,6,9]]){
 test(`chapter ${level}: actual opportunity gaps stay inside ${min}–${max} arrivals`,()=>{const m=run({level});const special=draw(m,150).filter(w=>POWERS.includes(w.kind));for(let i=1;i<special.length;i++)assert.ok(special[i].ordinal-special[i-1].ordinal>=min&&special[i].ordinal-special[i-1].ordinal<=max);assert.equal(special.length,m.economy.opportunities);});
}
for(const level of [6,12,18,24,30,36,42,48,54,102,198]){
 test(`trial ${level}: first opportunity in wave one, then one every eight arrivals`,()=>{const m=run({level,mode:level>48?'endless':'campaign'});assert.deepEqual(Object.values(m.inventory),[0,0,0,0]);const d=draw(m,40).filter(w=>POWERS.includes(w.kind));assert.equal(d[0].ordinal,4);assert.equal(d[0].kind,'ice');assert.equal(d[1].kind,'wind');for(let i=1;i<d.length;i++)assert.equal(d[i].ordinal-d[i-1].ordinal,8);for(let i=0;i+3<d.length;i+=4)assert.equal(new Set(d.slice(i,i+4).map(w=>w.kind)).size,4);});
}
test('first opportunity must be typed; merely appearing grants no spell',()=>{const m=run();const d=draw(m,6),w=d.at(-1);assert.equal(m.inventory.ice,0);m.setBuffer(w.text);m.submit();assert.equal(m.inventory.ice,1);assert.equal(m.economy.opportunities,1);});
test('missing the introductory ICE does not gift another tutorial set',()=>{const m=run();draw(m,6);const next=m.economy.untilNext;m.words[0].y=FIELD.bottom-.001;m.step();assert.equal(m.inventory.ice,0);assert.equal(m.missed,1);assert.ok(next>=8&&next<=11);assert.equal(m.economy.tutorialDone,true);});
test('burning a spell grants no inventory and does not accelerate its replacement opportunity',()=>{const m=run();draw(m,6);m.inventory.fire=1;const before={...m.economy};m.cast('fire');assert.equal(m.inventory.ice,0);assert.deepEqual(m.economy,before);assert.equal(m.burned,1);});
test('full shelves still cap at two; overflow remains a scored word, not another book',()=>{for(const p of POWERS){const m=run();m.inventory[p]=2;const w={id:1,text:'MAGIC',kind:p,x:500,y:300,speed:30};m.words=[w];m.setBuffer(w.text);m.submit();assert.equal(m.inventory[p],2);assert.equal(m.correct,1);assert.ok(m.score>0);assert.equal(m.drainEvents().find(e=>e.type==='correct').overflow,true);}});
test('entering a normal chapter does not restart the reward countdown or refill books',()=>{const m=run();draw(m,12);const before={...m.economy},bag=[...m.powerBag];m.inventory.ice=1;finish(m);m.nextLevel();assert.deepEqual(m.economy,before);assert.deepEqual(m.powerBag,bag);assert.equal(m.inventory.ice,1);const d=draw(m,before.untilNext);assert.equal(d.filter(w=>POWERS.includes(w.kind)).length,1);assert.ok(POWERS.includes(d.at(-1).kind));});
test('trial entry pulls a distant drop into wave one, without giving an extra one',()=>{const m=run({level:5});m.economy.untilNext=11;m.economy.tutorialDone=true;finish(m);m.nextLevel();assert.equal(m.economy.untilNext,4);assert.deepEqual(draw(m,20).filter(w=>POWERS.includes(w.kind)).map(w=>w.ordinal),[4,12,20]);});
test('an already due spell remains due rather than being delayed by trial setup',()=>{const m=run({level:5});m.economy.untilNext=1;finish(m);m.nextLevel();assert.deepEqual(draw(m,17).filter(w=>POWERS.includes(w.kind)).map(w=>w.ordinal),[1,9,17]);});
test('trial preferences never break the four-spell bag or grant free rescue inventory',()=>{const m=run({level:12});m.powerBag=['fire','slow'];const d=draw(m,20).filter(w=>POWERS.includes(w.kind));assert.deepEqual(d.slice(0,2).map(w=>w.kind),['fire','slow']);assert.deepEqual(Object.values(m.inventory),[0,0,0,0]);});
test('blocked candidate does not consume the countdown or a power-bag entry',()=>{const m=run({level:20});m.economy.untilNext=1;m.powerBag=['wind','fire'];m.words=[{id:1,text:'WWWWWWWWWW',kind:'normal',x:360,y:FIELD.top,width:410},{id:2,text:'VVVVVVVVVV',kind:'normal',x:700,y:FIELD.top,width:410}];const before=structuredClone(m.economy);assert.equal(m.spawn(),false);const pending=structuredClone(m.pendingSpawn);for(let i=0;i<100;i++)assert.equal(m.spawn(),false);assert.deepEqual(m.pendingSpawn,pending);assert.deepEqual(m.economy,before);assert.deepEqual(m.powerBag,['wind','fire']);m.words=[];assert.equal(m.spawn(),true);assert.equal(m.words[0].kind,'wind');assert.deepEqual(m.powerBag,['fire']);assert.equal(m.economy.opportunities,before.opportunities+1);});
test('canceling a reserved card at chapter clear never loses a bag entry',()=>{const m=run({level:20});m.economy.untilNext=1;m.powerBag=['wind','ice'];m.words=[{id:1,text:'W',x:360,y:FIELD.top,width:410},{id:2,text:'Q',x:700,y:FIELD.top,width:410}];assert.equal(m.spawn(),false);finish(m);m.nextLevel();assert.deepEqual(m.powerBag,['wind','ice']);assert.equal(m.economy.untilNext,1);draw(m,1);assert.equal(m.words[0].kind,'wind');});
test('pausing and waiting never manufacture or consume spell opportunities',()=>{const m=run();m.pause();const before=structuredClone(m.economy);for(let i=0;i<600;i++)m.step();assert.deepEqual(m.economy,before);});
test('active ICE freezes the scheduled arrival counter as well as card positions',()=>{const m=run();m.inventory.ice=1;m.cast('ice');const e={...m.economy};for(let i=0;i<300;i++)m.step();assert.deepEqual(m.economy,e);assert.equal(m.spawnedThisLevel,0);});
test('danger and score do not change scheduled spell types or gaps',()=>{const a=run({level:20}),b=run({level:20});b.danger=88;b.score=990000;assert.deepEqual(draw(a,120),draw(b,120));assert.deepEqual(a.economy,b.economy);});
test('each shuffled cycle still includes all four spells in all campaign wings',()=>{for(const level of [1,6,13,24,37,48,80]){const m=run({level});const d=draw(m,180).filter(w=>POWERS.includes(w.kind));for(let i=0;i+3<d.length;i+=4)assert.equal(new Set(d.slice(i,i+4).map(w=>w.kind)).size,4);}});
for(const level of [1,5,6,11,12,23,24,35,36,47]){
 test(`chapter ${level} boundary preserves words, spacing, cycle and inventory through save/restore`,()=>{const a=run({level});draw(a,11);a.inventory.wind=1;finish(a);const cp=a.checkpoint(),raw=mem(),s=new LocalStore(raw);assert.equal(s.setCheckpoint(cp),true);const b=run();b.restoreCheckpoint(new LocalStore(raw).checkpoint());a.nextLevel();assert.deepEqual(draw(a,40),draw(b,40));assert.deepEqual(a.economy,b.economy);assert.deepEqual(a.powerBag,b.powerBag);assert.deepEqual(a.inventory,b.inventory);});
}
test('retry starts the same sparse chapter again, without accumulating failed-attempt books',()=>{const a=run(),cp=a.checkpoint(),first=draw(a,12);a.inventory.ice=2;a.score=900;a.danger=99;a.setBuffer('ZZZ');a.submit();a.restoreCheckpoint(cp);assert.equal(a.score,0);assert.equal(a.inventory.ice,0);assert.deepEqual(draw(a,12),first);});
test('3.2 save migration caps stock at two, preserves mastery/preferences, and leaves original bytes untouched',()=>{const raw=mem(),cp=legacy(),old=JSON.stringify({version:3,settings:{music:false,adaptiveMusic:false,typingShimmer:false,volume:.32},checkpoints:{classic:cp},progress:{classic:{stages:{1:{medal:3,score:300,wpm:42,accuracy:99,ruleset:'typekeeper-3.2.0'}}}},records:[{score:990,level:4,pace:'classic',date:Date.now(),mode:'campaign',ruleset:'typekeeper-3.2.0'}]});raw.setItem('typekeeper-enchanted-library-v3.2',old);const s=new LocalStore(raw);assert.equal(raw.getItem('typekeeper-enchanted-library-v3.2'),old);assert.ok(raw.getItem('typekeeper-enchanted-library-v3.2.1'));assert.deepEqual(s.checkpoint().inventory,{fire:2,ice:2,slow:1,wind:2});assert.ok(validEconomy(s.checkpoint().economy));assert.equal(s.checkpoint().economy.tutorialDone,true);assert.equal(s.progress().unlocked,2);assert.equal(s.progress().stages[1].medal,3);assert.equal(s.settings.volume,.32);assert.equal(s.settings.music,false);assert.equal(s.settings.adaptiveMusic,false);assert.equal(s.settings.typingShimmer,false);assert.equal(s.records[0].mode,'legacy');});
test('migrated checkpoint keeps the old scoring provenance after new-rules play and re-export',()=>{const s=new LocalStore(mem());assert.equal(s.setCheckpoint(legacy()),true);const m=run();m.restoreCheckpoint(s.checkpoint());assert.equal(m.scoreRuleset,'typekeeper-3.2.0');s.add(m.result());assert.equal(s.records[0].mode,'legacy');assert.equal(JSON.parse(s.exportData()).appVersion,'3.4.0');});
test('fresh current saves cannot import a third charge by claiming the new ruleset',()=>{const s=new LocalStore(mem()),cp=run().checkpoint();cp.inventory.ice=3;assert.equal(s.validCheckpoint(cp),false);assert.equal(s.setCheckpoint(cp),false);});
test('current saves must include a valid schedule; old missing schedules have an explicit fallback',()=>{const s=new LocalStore(mem()),cp=run().checkpoint();delete cp.economy;assert.equal(s.validCheckpoint(cp),false);cp.ruleset='typekeeper-3.2.0';assert.equal(s.setCheckpoint(cp),true);assert.equal(s.checkpoint().economy.untilNext,8);assert.equal(s.checkpoint().economy.tutorialDone,true);});
test('invalid schedule values are rejected rather than granting unlimited imminent drops',()=>{const s=new LocalStore(mem()),cp=run().checkpoint();for(const patch of [{untilNext:0},{untilNext:12},{untilNext:1.5},{untilNext:NaN},{opportunities:-1},{opportunities:Infinity},{version:9},{tutorialDone:1}])assert.equal(s.validCheckpoint({...cp,economy:{...cp.economy,...patch}}),false);});
test('restored inventory and schedule are isolated from imported object mutations',()=>{const cp=run().checkpoint(),m=run();m.restoreCheckpoint(cp);cp.economy.untilNext=1;cp.inventory.ice=2;assert.equal(m.economy.untilNext,6);assert.equal(m.inventory.ice,0);});
test('model restore also clamps legacy charges when called directly by a trusted loader',()=>{const m=run();m.restoreCheckpoint(legacy());assert.deepEqual(m.inventory,{fire:2,ice:2,slow:1,wind:2});});
test('authored non-trial gap endpoints are reachable and trial setup is idempotent',()=>{for(const level of [1,7,13,25,49]){const c=economyRules(level);assert.equal(nextSpellGap(level,()=>0),c.minGap);assert.equal(nextSpellGap(level,()=>.9999999),c.maxGap);}const e=createEconomy();prepareEconomy(e,6);const once={...e};prepareEconomy(e,6);assert.deepEqual(e,once);});
test('Practice and Endless do not receive the campaign introduction again',()=>{for(const mode of ['practice','endless'])assert.equal(createEconomy(1,mode).tutorialDone,true);});
test('UI stock pips derive from the same authoritative capacity as game rules',()=>{const src=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');assert.ok(src.includes("'<i></i>'.repeat(RULES.inventoryCapacity)"));assert.ok(src.includes('Store up to two of each spell.'));assert.ok(!src.includes('Store up to three of each spell.'));});
