import test from 'node:test';
import assert from 'node:assert/strict';
import {GameModel} from '../src/game/model.js';
import {RULES,FIELD,POWERS,normalizeInput,scoreForWord,mulberry32,levelRules,wordCardWidth} from '../src/game/rules.js';
import {WORD_BANK,WORD_COUNT} from '../src/data/words.js';
import {FixedClock} from '../src/game/clock.js';
import {LocalStore} from '../src/game/storage.js';
function run(seed=33){const m=new GameModel();m.start({seed});m.drainEvents();return m;}
function word(m,text='BOOK',kind='normal',y=300){const w={id:m.nextId++,text,kind,x:500,y,previousY:y,speed:30,width:120,phase:1};m.words.push(w);return w;}
function submit(m,text){m.setBuffer(text);return m.submit();}
function step(m,seconds){for(let i=0;i<Math.round(seconds*60);i++)m.step(1/60);}
function memoryStore(){const state=new Map();return{getItem:k=>state.get(k),setItem:(k,v)=>state.set(k,v),state};}

test('normalization accepts English letters, uppercases and bounds the buffer',()=>{assert.equal(normalizeInput('  a!b1c é'),'ABC');assert.equal(normalizeInput('z'.repeat(40)).length,24);});
test('dictionary is substantial, uppercase, unique within tiers, and all words fit the buffer',()=>{assert.ok(WORD_COUNT>500);for(const list of Object.values(WORD_BANK)){assert.equal(new Set(list).size,list.length);for(const w of list){assert.match(w,/^[A-Z]+$/);assert.ok(w.length<=24);}}});
test('seeded random generator repeats exactly',()=>{const a=mulberry32(9),b=mulberry32(9);assert.deepEqual(Array.from({length:100},a),Array.from({length:100},b));});
test('fresh game is in menu, with no starting power stock',()=>{const m=new GameModel();assert.equal(m.phase,'menu');assert.equal(Object.values(m.inventory).reduce((a,b)=>a+b),0);});
test('start resets all run state',()=>{const m=run();m.score=900;m.effects.ice=3;m.inventory.fire=2;m.danger=61;m.words.push({});m.start({seed:5});assert.equal(m.score,0);assert.equal(m.words.length,0);assert.equal(m.danger,0);assert.equal(m.effects.ice,0);assert.equal(m.inventory.fire,0);});
test('complete exact word once, update points/progress/characters',()=>{const m=run(),w=word(m);assert.equal(submit(m,'book'),'word');assert.equal(m.words.length,0);assert.equal(m.score,40);assert.equal(m.progress,1);assert.equal(m.correctCharacters,4);m.complete(w);assert.equal(m.score,40);});
test('partial input never auto-clears or penalizes',()=>{const m=run();word(m);m.setBuffer('BO');assert.equal(m.words.length,1);assert.equal(m.danger,0);assert.equal(m.wrong,0);m.setBuffer('BOOK');assert.equal(m.words.length,1);});
test('empty Enter is a true no-op',()=>{const m=run();assert.equal(m.submit(),null);assert.equal(m.wrong,0);assert.equal(m.score,0);});
test('invalid submission penalizes once and clears the buffer',()=>{const m=run();word(m);submit(m,'WRONG');assert.equal(m.danger,2);assert.equal(m.wrong,1);assert.equal(m.buffer,'');m.submit();assert.equal(m.wrong,1);});
test('editing a prefix is non-destructive',()=>{const m=run();word(m,'GARDEN');m.setBuffer('GARD');m.setBuffer('GAR');m.setBuffer('GARDEN');m.submit();assert.equal(m.correct,1);assert.equal(m.wrong,0);});
test('duplicate words resolve the lowest exact match',()=>{const m=run(),a=word(m,'TALE','normal',200),b=word(m,'TALE','normal',520);submit(m,'TALE');assert.deepEqual(m.words.map(w=>w.id),[a.id]);assert.notEqual(a.id,b.id);});
test('ties are stable by ID',()=>{const m=run(),a=word(m,'TALE'),b=word(m,'TALE');submit(m,'TALE');assert.equal(m.words[0].id,b.id);});
test('shared prefix does not lock onto a target',()=>{const m=run();word(m,'STAR');word(m,'START');submit(m,'START');assert.equal(m.words[0].text,'STAR');});
test('falling FIRE word takes priority over available command',()=>{const m=run();word(m,'FIRE');word(m,'KEEP');m.inventory.fire=1;submit(m,'FIRE');assert.equal(m.inventory.fire,1);assert.equal(m.words.length,1);assert.equal(m.correct,1);});
test('power collection is immediate and capped at two',()=>{const m=run();m.inventory.ice=1;word(m,'SNOW','ice');submit(m,'SNOW');assert.equal(m.inventory.ice,2);word(m,'FROST','ice');submit(m,'FROST');assert.equal(m.inventory.ice,2);assert.equal(m.correct,2);});
test('all four power-card families grant the corresponding book',()=>{const m=run();for(const p of POWERS){word(m,'MAGIC',p);submit(m,'MAGIC');assert.equal(m.inventory[p],1);}});
test('unavailable spell costs no points or danger and grants no stock',()=>{const m=run();assert.equal(submit(m,'FIRE'),'empty-power');assert.equal(m.inventory.fire,0);assert.equal(m.danger,0);assert.equal(m.wrong,0);});
test('FIRE clears active cards without scoring, progress, or harvesting books',()=>{const m=run();const w=word(m,'FROST','ice',657);word(m,'GOLD','bonus');m.inventory.fire=1;submit(m,'FIRE');assert.equal(m.words.length,0);assert.equal(m.score,0);assert.equal(m.progress,0);assert.equal(m.inventory.ice,0);assert.equal(m.inventory.fire,0);m.complete(w);step(m,.05);assert.equal(m.missed,0);});
test('FIRE consumes exactly one charge per nonempty cast',()=>{const m=run();word(m);m.inventory.fire=2;submit(m,'FIRE');m.submit();assert.equal(m.inventory.fire,1);assert.equal(m.casts.fire,1);});
test('ICE stops words and spawn timer for its duration',()=>{const m=run(),w=word(m);m.spawnClock=2;m.inventory.ice=1;submit(m,'ICE');step(m,2);assert.equal(w.y,300);assert.equal(m.spawnClock,2);assert.ok(Math.abs(m.effects.ice-4)<.00001);});
test('ICE active recast is rejected and preserves the next book',()=>{const m=run();m.inventory.ice=2;submit(m,'ICE');step(m,2);const duration=m.effects.ice;submit(m,'ICE');assert.equal(m.effects.ice,duration);assert.equal(m.inventory.ice,1);});
test('SLOW scales motion by exactly 0.42',()=>{const m=run(),w=word(m);m.spawnClock=90;m.inventory.slow=1;submit(m,'SLOW');step(m,1);assert.ok(Math.abs(w.y-(300+30*.42))<.001);});
test('ICE and SLOW coexist; SLOW time is banked until ICE ends',()=>{const m=run(),w=word(m);m.inventory.ice=1;m.inventory.slow=1;submit(m,'SLOW');submit(m,'ICE');step(m,2);assert.equal(w.y,300);assert.ok(Math.abs(m.effects.ice-4)<.001);assert.ok(Math.abs(m.effects.slow-8)<.001);});
test('WIND fully clears danger and paper without clearing active words',()=>{const m=run();word(m);m.pile=[{id:1}];m.danger=95;m.inventory.wind=1;submit(m,'WIND');assert.equal(m.danger,0);assert.equal(m.pile.length,0);assert.equal(m.words.length,1);});
test('pause freezes timers, positions, game time, and spawn countdown',()=>{const m=run();word(m);m.effects.ice=5;m.pause();const s=m.snapshot();step(m,10);assert.deepEqual(m.snapshot(),s);m.resume();step(m,1);assert.ok(m.time>.9);});
test('paused input cannot change buffer or score',()=>{const m=run();word(m);m.setBuffer('BO');m.pause();m.setBuffer('BOOK');m.submit();assert.equal(m.buffer,'BO');assert.equal(m.score,0);});
test('miss adds the configured danger once and clears streak',()=>{const m=run();m.spawnClock=20;word(m,'BOOK','normal',FIELD.bottom-.1);m.streak=9;step(m,.05);assert.equal(m.missed,1);assert.equal(m.streak,0);assert.ok(Math.abs(m.danger-11.2)<.001);assert.equal(m.pile.length,1);});
test('dark miss penalty is larger; dark completion earns double',()=>{const m=run();m.spawnClock=20;word(m,'BOOK','bonus',FIELD.bottom-.1);step(m,.05);assert.ok(Math.abs(m.danger-16.8)<.001);const n=run();word(n,'BOOK','bonus');submit(n,'BOOK');assert.equal(n.score,80);});
test('game over is terminal and emits only once',()=>{const m=run();m.danger=99;m.spawnClock=99;word(m,'BOOK','normal',FIELD.bottom-.1);step(m,1);assert.equal(m.phase,'game-over');assert.equal(m.danger,100);assert.equal(m.drainEvents().filter(e=>e.type==='game-over').length,1);const score=m.score;submit(m,'BOOK');step(m,5);assert.equal(m.score,score);assert.equal(m.drainEvents().filter(e=>e.type==='game-over').length,0);});
test('an invalid submission can end a run at the limit',()=>{const m=run();m.danger=99;submit(m,'INVALID');assert.equal(m.phase,'game-over');assert.equal(m.danger,100);});
test('word submitted just before impact cannot subsequently land',()=>{const m=run();m.spawnClock=99;word(m,'BOOK','normal',FIELD.bottom-.01);submit(m,'BOOK');step(m,.1);assert.equal(m.correct,1);assert.equal(m.missed,0);});
test('perfect chapter awards 100 x level plus 250, then clears field',()=>{const m=run();m.danger=12;m.inventory.wind=2;for(let i=0;i<12;i++){word(m,'BOOK');submit(m,'BOOK');}assert.equal(m.phase,'level-clear');assert.equal(m.stageBonus,350);assert.equal(m.progress,12);assert.equal(m.words.length,0);assert.equal(m.danger,12);assert.equal(m.inventory.wind,2);});
test('imperfect chapter excludes perfect bonus',()=>{const m=run();submit(m,'WRONG');for(let i=0;i<12;i++){word(m,'BOOK');submit(m,'BOOK');}assert.equal(m.stageBonus,100);});
test('next chapter resets quota and timed effects but retains danger and stock',()=>{const m=run();m.danger=30;m.inventory.fire=2;m.effects.ice=5;for(let i=0;i<12;i++){word(m,'BOOK');submit(m,'BOOK');}m.nextLevel();assert.equal(m.phase,'playing');assert.equal(m.level,2);assert.equal(m.config.quota,12);assert.equal(m.danger,30);assert.equal(m.inventory.fire,2);assert.equal(m.effects.ice,0);assert.equal(m.progress,0);});
test('streak multiplier grows at eight and caps at three',()=>{assert.equal(scoreForWord('BOOK','normal',7),40);assert.equal(scoreForWord('BOOK','normal',8),50);assert.equal(scoreForWord('BOOK','normal',999),120);});
test('word accuracy is submission accuracy, not a keystroke claim',()=>{const m=run();word(m);submit(m,'BOOK');submit(m,'BAD');assert.equal(m.accuracy,50);});
test('WPM uses correctly completed characters and active time',()=>{const m=run();m.time=60;m.correctCharacters=250;assert.equal(m.wpm,50);});
test('same seed and input sequence yield the same simulation',()=>{const a=run(2012),b=run(2012);for(let i=0;i<800;i++){a.step();b.step();if(i%90===0&&a.words[0]){submit(a,a.words[0].text);submit(b,b.words[0].text);}}assert.deepEqual(a.snapshot(),b.snapshot());assert.deepEqual(a.exportReplay(),b.exportReplay());});
test('spawn bounds keep whole cards on the playfield',()=>{const m=run();for(let i=0;i<90;i++){m.level=1+Math.floor(i/5);m.words=[];assert.ok(m.spawn());const w=m.words[0];assert.ok(w.x-w.width/2>=FIELD.left);assert.ok(w.x+w.width/2<=FIELD.right);assert.equal(w.y,FIELD.top);}});
test('spawn is bounded at 12 simultaneous cards',()=>{const m=run();for(let i=0;i<12;i++)word(m,'BOOK','normal',400);assert.equal(m.spawn(),false);assert.equal(m.words.length,12);});
test('special cards include explicit glyph padding',()=>{const m=run();m.economy.untilNext=1;m.spawn();const w=m.words[0];assert.equal(w.kind,'ice');assert.ok(w.width>=112);assert.ok(w.width>wordCardWidth(w.text,'normal'));});
test('level speed and quotas increase but remain bounded',()=>{assert.ok(levelRules(5).speed>levelRules(1).speed);assert.equal(levelRules(100).quota,42);assert.ok(levelRules(100).interval>=.65);assert.ok(levelRules(100).speed<=170);});
test('pace choice changes speed without changing correctness rules',()=>{assert.ok(levelRules(1,'relaxed').speed<levelRules(1).speed);assert.ok(levelRules(1,'maniac').speed>levelRules(1).speed);});
test('fixed clock creates 60 bounded simulation steps over one second',()=>{const c=new FixedClock(),ticks=[];c.advance(0,dt=>ticks.push(dt));for(let i=1;i<=60;i++)c.advance(i*1000/60,dt=>ticks.push(dt));assert.ok(ticks.length>=59&&ticks.length<=60);assert.ok(ticks.every(x=>x===1/60));});
test('clock does not simulate a hidden-tab catch-up burst',()=>{const c=new FixedClock();let n=0;c.advance(0,()=>n++);c.advance(60000,()=>n++,false);c.reset();c.advance(60001,()=>n++);assert.equal(n,0);c.advance(61000,()=>n++);assert.ok(n<=6);});
test('settings and local records round-trip with schema validation',()=>{const raw=memoryStore(),s=new LocalStore(raw);s.update({music:true});s.add({score:1234,level:2,pace:'classic',wpm:44});const t=new LocalStore(raw);assert.equal(t.settings.music,true);assert.equal(t.best(),1234);assert.equal(t.records.length,1);});
test('malformed local data recovers safely',()=>{const s=new LocalStore({getItem:()=>'{bad',setItem:()=>{}});assert.equal(s.records.length,0);s.save();assert.equal(s.available,true);});
test('unavailable storage is explicitly session-only',()=>{const s=new LocalStore(undefined);assert.equal(s.available,false);s.add({score:4,level:1,pace:'classic'});assert.equal(s.records.length,1);assert.equal(s.available,false);});
test('blocked storage never crashes game state',()=>{const s=new LocalStore({getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}});s.add({score:123,level:1,pace:'classic'});assert.equal(s.available,false);assert.equal(s.records.length,1);});
test('records filter malformed entries and maintain independent pace bests',()=>{const raw=memoryStore();raw.setItem('typing-maniac-library-v1',JSON.stringify({version:1,records:[{score:-10,level:1,date:2,pace:'classic'},null,{score:50,level:1,date:2,pace:'maniac'}]}));const s=new LocalStore(raw);assert.equal(s.records.length,1);assert.equal(s.best('classic'),0);assert.equal(s.best('maniac'),0);assert.equal(s.records[0].mode,'legacy');});
test('clearing records retains settings',()=>{const s=new LocalStore(memoryStore());s.update({music:true});s.add({score:20,level:1,pace:'classic'});s.clearRecords();assert.equal(s.records.length,0);assert.equal(s.settings.music,true);});
