import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {campaignEntryState} from '../src/ui/campaign-entry.js';
import {GameModel} from '../src/game/model.js';
import {LocalStore} from '../src/game/storage.js';
import {RULESET_VERSION} from '../src/game/rules.js';
const KEY='typekeeper-enchanted-library-v3.2.1';
function memory(){const data=new Map(),writes=[];return {data,writes,getItem:k=>data.get(k)||null,setItem:(k,v)=>{data.set(k,v);writes.push(JSON.parse(v));}};}
function fixture(pace='classic',last=11){const backing=memory(),s=new LocalStore(backing),m=new GameModel();for(let n=1;n<=last;n++)s.completeStage(pace,{level:n,medal:3,stageScore:n*1000,wpm:75,accuracy:100,ruleset:RULESET_VERSION});m.start({seed:123,pace});m.level=last+1;m.score=5500;m.danger=24;m.prepareStage();s.setCheckpoint(m.checkpoint());s.recordChapter(pace,'practice',{level:5,stageScore:2500,medal:3,wpm:90,accuracy:100,words:14,wrong:0,missed:0,seconds:20,ruleset:RULESET_VERSION},{seed:999});s.recordScoreChase({pace,mode:'campaign',startLevel:1,level:1,score:1580});s.add({pace,mode:'campaign',level:6,startLevel:1,score:9000,ruleset:RULESET_VERSION});return {backing,s,m};}
const permanent=s=>structuredClone({progress:s.data.progress,records:s.data.records,chapterBests:s.data.chapterBests,scoreChaseBests:s.data.scoreChaseBests,settings:s.data.settings});
test('New player has exactly the original Play entry and no unnecessary restart',()=>{assert.deepEqual(campaignEntryState({unlocked:1,stages:{}}),{hasProgress:false,canContinue:false,showRestart:false,primaryLabel:'Play',primaryAction:'start'});});
for(const chapter of [1,2,12,24,48])test(`A Chapter ${chapter} Continue point exposes a separate restart choice`,()=>{const v=campaignEntryState({unlocked:chapter,stages:{}},{nextLevel:chapter});assert.equal(v.primaryAction,'continue');assert.equal(v.primaryLabel,'Continue');assert.equal(v.showRestart,true);});
for(const state of [{unlocked:12,stages:{}},{unlocked:48,stages:{48:{medal:3}}},{unlocked:1,stages:{1:{medal:1}}}])test(`Historical progress without a checkpoint gets explicit Chapter 1 copy: ${JSON.stringify(state)}`,()=>{const v=campaignEntryState(state);assert.equal(v.primaryAction,'new-confirm');assert.equal(v.primaryLabel,'Start from Chapter 1');assert.equal(v.showRestart,false);});
test('A prior recorded campaign without unlocks is still a returning player',()=>assert.equal(campaignEntryState({unlocked:1,stages:{}},null,true).hasProgress,true));
test('Entry choices never mutate progress/checkpoint inputs and are immutable',()=>{const p=Object.freeze({unlocked:12,stages:Object.freeze({})}),c=Object.freeze({nextLevel:12});const result=campaignEntryState(p,c);assert(Object.isFrozen(result));assert.equal(p.unlocked,12);assert.equal(c.nextLevel,12);});
for(const pace of ['classic','relaxed','maniac']){
 test(`${pace}: replacing Continue with Chapter 1 preserves every permanent collection`,()=>{const {s,m}=fixture(pace);const before=permanent(s);m.start({seed:456,pace});assert(s.setCheckpoint(m.checkpoint()));assert.deepEqual(permanent(s),before);const cp=s.checkpoint(pace);assert.equal(cp.nextLevel,1);assert.equal(cp.score,0);assert.equal(cp.danger,0);assert.equal(m.level,1);assert.equal(m.mode,'campaign');assert.equal(m.startLevel,1);assert.equal(m.score,0);assert(Object.values(m.inventory).every(n=>n===0));assert.equal(s.progress(pace).unlocked,12);});
 test(`${pace}: replaying an earlier chapter cannot relock later chapters or reduce mastery`,()=>{const {s,m}=fixture(pace);m.start({seed:456,pace});s.setCheckpoint(m.checkpoint());s.completeStage(pace,{level:1,medal:1,stageScore:100,wpm:25,accuracy:75,ruleset:RULESET_VERSION});assert.equal(s.progress(pace).unlocked,12);assert.equal(s.progress(pace).stages[1].medal,3);assert.equal(s.progress(pace).stages[1].score,1000);});
 test(`${pace}: new journey survives reload with unlocked chapter selection intact`,()=>{const {s,m,backing}=fixture(pace);m.start({seed:456,pace});s.setCheckpoint(m.checkpoint());const reread=new LocalStore(backing);assert.equal(reread.checkpoint(pace).nextLevel,1);assert.deepEqual(permanent(reread),permanent(s));const resume=new GameModel();resume.restoreCheckpoint(reread.checkpoint(pace));assert.equal(resume.level,1);assert.equal(resume.score,0);});
 test(`${pace}: unlocked late-chapter practice leaves the fresh campaign Continue point untouched`,()=>{const {s,m}=fixture(pace);m.start({seed:456,pace});s.setCheckpoint(m.checkpoint());const cp=s.checkpoint(pace);m.start({seed:999,pace,mode:'practice',level:12});s.completeStage(pace,{level:12,medal:2,stageScore:100,wpm:30,accuracy:80,ruleset:RULESET_VERSION},false);assert.deepEqual(s.checkpoint(pace),cp);assert.equal(s.progress(pace).unlocked,12);assert.equal(s.progress(pace).stages[12].campaignClear,false);});
}
test('Other difficulties retain their own Continue points and progression',()=>{const {s,m}=fixture();for(const pace of ['relaxed','maniac']){const a=new GameModel();a.start({seed:92,pace,level:3});s.setCheckpoint(a.checkpoint());}const before={relaxed:s.checkpoint('relaxed'),maniac:s.checkpoint('maniac')};m.start({seed:56,pace:'classic'});s.setCheckpoint(m.checkpoint());assert.deepEqual(s.checkpoint('relaxed'),before.relaxed);assert.deepEqual(s.checkpoint('maniac'),before.maniac);});
test('Replacing the checkpoint uses a single valid complete save, with no deletion gap',()=>{const {s,m,backing}=fixture();backing.writes.length=0;m.start({seed:56,pace:'classic'});s.setCheckpoint(m.checkpoint());assert.equal(backing.writes.length,1);assert.equal(backing.writes[0].checkpoints.classic.nextLevel,1);assert.equal(backing.writes[0].progress.classic.unlocked,12);});
test('A rejected/corrupt replacement cannot delete the prior valid Continue point',()=>{const {s}=fixture(),before=s.checkpoint();assert.equal(s.setCheckpoint({nextLevel:1}),false);assert.deepEqual(s.checkpoint(),before);});
test('Storage write failure leaves old saved bytes intact and keeps progress in the session',()=>{const {s,m,backing}=fixture();const before=backing.getItem(KEY),progress=permanent(s);backing.setItem=()=>{throw new Error('QuotaExceededError');};m.start({seed:44});s.setCheckpoint(m.checkpoint());assert.equal(s.available,false);assert.equal(backing.getItem(KEY),before);assert.deepEqual(permanent(s),progress);assert.equal(s.checkpoint().nextLevel,1);});
test('Export/import after restart retains the new checkpoint, old stars, chapter PBs and Score Chase',()=>{const {s,m}=fixture();m.start({seed:55});s.setCheckpoint(m.checkpoint());const s2=new LocalStore(memory());s2.importData(JSON.parse(s.exportData()));assert.deepEqual(permanent(s2),permanent(s));assert.deepEqual(s2.checkpoint(),s.checkpoint());});
test('New Chapter 1 uses only the matching cumulative BEST, never a later chapter total',()=>{const {s,m}=fixture();s.recordScoreChase({pace:'classic',mode:'campaign',startLevel:1,level:12,score:999999});m.start({seed:99});const best=s.scoreChaseBest({ruleset:RULESET_VERSION,pace:'classic',mode:'campaign',chapter:1,startLevel:1});assert.equal(best.score,1580);});
test('Source guard prevents stale or duplicate confirmations from reseeding an active run',()=>{const s=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');assert.match(s,/if\(view!=='new-confirm'\|\|!request\)return/);assert.match(s,/case 'fresh-start':confirmFreshStart\(\)/);assert.match(s,/freshRequest=null;start\(undefined,1,'campaign'\)/);assert(!s.includes("if(mode==='campaign')store.clearCheckpoint"));});
const pins=JSON.parse(fs.readFileSync(new URL('./fixtures/v360-restart-preserved.json',import.meta.url)));
for(const [file,sha] of Object.entries(pins.sha256).filter(([file])=>file!=='src/render/renderer.js'))test(`v3.6.2 foundation unchanged outside Open Atrium renderer: ${file}`,()=>assert.equal(createHash('sha256').update(fs.readFileSync(new URL('../'+file,import.meta.url))).digest('hex'),sha));
