import test from 'node:test';
import assert from 'node:assert/strict';
import { GameModel } from '../src/game/model.js';
import { RULES, POWERS, levelRules, wordCardWidth, FIELD } from '../src/game/rules.js';
import { CAMPAIGN, WINGS, CAMPAIGN_LENGTH, stageInfo, medalForStage } from '../src/data/campaign.js';
import { pressureState } from '../src/game/pressure.js';
import { powerForKey } from '../src/game/controls.js';
import { LocalStore } from '../src/game/storage.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};};
function run(options={}){const m=new GameModel();m.start({seed:4096,...options});m.drainEvents();return m;}
function add(m,text='BOOK',kind='normal',y=350){m.words.push({id:m.nextId++,text,kind,x:500,y,previousY:y,speed:m.config.speed,width:wordCardWidth(text,kind),phase:0});}
function clearStage(m){const quota=m.config.quota;for(let i=m.progress;i<quota;i++){add(m);m.setBuffer('BOOK');m.submit();}return m.lastClear;}
function advance(m,n){for(let i=0;i<Math.round(n*60);i++)m.step();}

test('campaign has 48 unique named stages across eight six-stage wings',()=>{assert.equal(CAMPAIGN_LENGTH,48);assert.equal(CAMPAIGN.length,48);assert.equal(WINGS.length,8);assert.equal(new Set(CAMPAIGN.map(s=>s.title)).size,48);for(let i=0;i<48;i++){assert.equal(CAMPAIGN[i].level,i+1);assert.equal(CAMPAIGN[i].wing,Math.floor(i/6)+1);}});
test('eight trials occur at the end of each wing',()=>{assert.deepEqual(CAMPAIGN.filter(s=>s.trial).map(s=>s.level),[6,12,18,24,30,36,42,48]);});
test('all 48 stages have smooth rising speed and falling arrival interval',()=>{for(const pace of ['classic','relaxed','maniac']){for(let i=2;i<=48;i++){const a=levelRules(i-1,pace),b=levelRules(i,pace);assert.ok(b.speed>a.speed);assert.ok(b.speed/a.speed<1.13);assert.ok(b.interval<a.interval);assert.ok(b.quota<=42);}}});
test('endless mode is named and has bounded speed and spawn intervals',()=>{assert.equal(stageInfo(49).endless,true);assert.equal(levelRules(10000).speed,170);assert.equal(levelRules(10000).interval,.78);});
test('every numbered hotkey and numpad key maps to its spell',()=>{for(let i=1;i<=4;i++){assert.equal(powerForKey({code:'Digit'+i,key:String(i)}),POWERS[i-1]);assert.equal(powerForKey({code:'Numpad'+i,key:String(i)}),POWERS[i-1]);}});
test('hotkeys ignore modifiers, key repeat, IME and ordinary typing',()=>{for(const key of ['metaKey','ctrlKey','altKey','shiftKey','repeat','isComposing'])assert.equal(powerForKey({code:'Digit1',key:'1',[key]:true}),null);assert.equal(powerForKey({code:'KeyF',key:'f'}),null);});
test('quick cast preserves the typed buffer and records input provenance',()=>{const m=run();add(m);m.inventory.ice=1;m.setBuffer('BOO');m.cast('ice','hotkey');assert.equal(m.buffer,'BOO');assert.equal(m.inventory.ice,0);assert.equal(m.exportReplay().events.at(-1).type,'cast');});
test('quick FIRE is unambiguous even with a falling FIRE word',()=>{const m=run();add(m,'FIRE');m.inventory.fire=1;m.setBuffer('FI');assert.equal(m.cast('fire','hotkey'),true);assert.equal(m.buffer,'FI');assert.equal(m.words.length,0);assert.equal(m.score,0);});
test('empty FIRE does not waste inventory',()=>{const m=run();m.inventory.fire=2;assert.equal(m.cast('fire'),false);assert.equal(m.inventory.fire,2);assert.equal(m.drainEvents().at(-1).reason,'empty-field');});
test('empty WIND does not waste inventory',()=>{const m=run();m.inventory.wind=2;assert.equal(m.cast('wind'),false);assert.equal(m.inventory.wind,2);});
test('active SLOW cannot waste a second book',()=>{const m=run();m.inventory.slow=2;m.cast('slow');advance(m,1);const left=m.effects.slow;assert.equal(m.cast('slow'),false);assert.equal(m.effects.slow,left);assert.equal(m.inventory.slow,1);});
test('SLOW creates breathing room in spawn countdown as well as motion',()=>{const m=run();m.spawnClock=10;m.inventory.slow=1;m.cast('slow');advance(m,1);assert.ok(Math.abs(m.spawnClock-9.3)<1e-6);});
test('casting after ICE expires consumes the next book once',()=>{const m=run();m.inventory.ice=2;m.cast('ice');advance(m,6.1);assert.equal(m.effects.ice,0);assert.equal(m.cast('ice'),true);assert.equal(m.inventory.ice,0);});
test('anti-doublecast cooldown applies per power without blocking combinations',()=>{const m=run();add(m);m.inventory.fire=2;m.inventory.ice=1;m.cast('fire');add(m);assert.equal(m.cast('fire'),false);assert.equal(m.inventory.fire,1);assert.equal(m.cast('ice'),true);advance(m,.3);assert.equal(m.cast('fire'),true);});
test('pressure state thresholds include every exact boundary',()=>{for(const [n,k] of [[0,'calm'],[24.99,'calm'],[25,'focused'],[49.99,'focused'],[50,'worried'],[75,'alarmed'],[90,'critical']])assert.equal(pressureState(n).key,k);});
test('defeat and celebration override the normal pressure expression',()=>{assert.equal(pressureState(100,'game-over').key,'defeated');assert.equal(pressureState(95,'level-clear').key,'celebrate');});
test('WIND immediately restores the calm gameplay state',()=>{const m=run();m.danger=96;m.inventory.wind=1;assert.equal(m.pressure.key,'critical');m.cast('wind');assert.equal(m.pressure.key,'calm');});
test('pressure events fire on transitions rather than every frame',()=>{const m=run();m.danger=70;m.checkPressure();m.checkPressure();m.checkPressure();assert.equal(m.drainEvents().filter(e=>e.type==='pressure').length,1);m.danger=91;m.checkPressure();assert.equal(m.drainEvents().filter(e=>e.type==='pressure').length,1);});
test('mastery stars use documented gold, silver and bronze thresholds',()=>{assert.equal(medalForStage({}),3);assert.equal(medalForStage({missed:2,wrong:3}),2);assert.equal(medalForStage({missed:3,wrong:0}),1);assert.equal(medalForStage({missed:0,wrong:4}),1);});
test('stage summaries use stage-local WPM and accuracy',()=>{const m=run();m.time=120;m.correctCharacters=600;m.stageTime=30;m.stageCharacters=100;clearStage(m);assert.equal(m.lastClear.words,12);assert.equal(m.lastClear.accuracy,100);assert.equal(m.lastClear.wpm,Math.round(148/5/.5));assert.equal(m.lastClear.medal,3);});
test('a full campaign advances through all 48 stages without stale phase or progress',()=>{const m=run();for(let n=1;n<=48;n++){assert.equal(m.level,n);const summary=clearStage(m);assert.equal(summary.level,n);assert.equal(m.phase,'level-clear');assert.equal(m.words.length,0);if(n<48){m.nextLevel();assert.equal(m.progress,0);assert.equal(m.stageTime,0);}}assert.equal(m.stageHistory.length,48);assert.equal(m.finishCampaign().victory,true);assert.equal(m.finishCampaign().medals,144);});
test('checkpoint restores score, books, danger and completed stages at the next boundary',()=>{const m=run();m.danger=43;m.inventory.ice=2;clearStage(m);const checkpoint=m.checkpoint(),n=run();n.restoreCheckpoint(checkpoint);assert.equal(n.level,2);assert.equal(n.score,m.score);assert.equal(n.inventory.ice,2);assert.equal(n.danger,43);assert.equal(n.stageHistory.length,1);assert.equal(n.progress,0);assert.equal(n.stageTime,0);});
test('checkpoint is validated before being saved',()=>{const s=new LocalStore(memory()),m=run();clearStage(m);const cp=m.checkpoint();assert.ok(s.validCheckpoint(cp));s.setCheckpoint(cp);assert.equal(s.checkpoint().nextLevel,2);assert.equal(s.validCheckpoint({...cp,danger:100}),false);assert.equal(s.validCheckpoint({...cp,nextLevel:49}),false);assert.equal(s.validCheckpoint({...cp,inventory:{...cp.inventory,fire:9}}),false);});
test('checkpoint survives actual store serialization and clear is persistent',()=>{const raw=memory(),s=new LocalStore(raw),m=run();clearStage(m);s.setCheckpoint(m.checkpoint());const next=new LocalStore(raw);assert.equal(next.checkpoint().nextLevel,2);next.clearCheckpoint('classic');assert.equal(new LocalStore(raw).checkpoint(),null);});
test('mastery keeps the best grade and paces stay independent',()=>{const s=new LocalStore(memory());s.completeStage('classic',{level:1,medal:3,stageScore:100,wpm:50,accuracy:100});s.completeStage('classic',{level:1,medal:1,stageScore:50,wpm:40,accuracy:50});assert.equal(s.progress().stages[1].medal,3);assert.equal(s.progress().unlocked,2);assert.equal(s.progress('maniac').unlocked,1);});
test('practice can improve an earned grade but cannot create expedition progress',()=>{const s=new LocalStore(memory());s.completeStage('classic',{level:1,medal:2,stageScore:100,wpm:40,accuracy:90},false);assert.equal(s.progress().unlocked,1);assert.equal(s.progress().stages[1].campaignClear,false);s.completeStage('classic',{level:1,medal:1,stageScore:100,wpm:40,accuracy:90});s.completeStage('classic',{level:1,medal:3,stageScore:200,wpm:50,accuracy:100},false);assert.equal(s.progress().unlocked,2);assert.equal(s.progress().stages[1].medal,3);});
test('save export/import merges rather than duplicates records',()=>{const a=new LocalStore(memory());a.add({score:100,level:2,pace:'classic',seed:4});const b=new LocalStore(memory());b.importData(JSON.parse(a.exportData()));b.importData(JSON.parse(a.exportData()));assert.equal(b.records.length,1);assert.equal(b.best(),100);});
test('current, practice and legacy records are not mixed in best score',()=>{const s=new LocalStore(memory());s.add({score:100,level:2,pace:'classic'});s.add({score:999,level:48,pace:'classic',mode:'practice'});s.add({score:8888,level:48,pace:'classic',ruleset:'library-edition-1.0.0',mode:'legacy'});assert.equal(s.best(),100);assert.equal(s.best('classic','practice'),999);assert.equal(s.filteredRecords({mode:'legacy'}).length,1);});
test('record time windows use date cutoffs and actual records',()=>{const s=new LocalStore(memory()),now=Date.now();s.data.records=[{score:1,pace:'classic',mode:'campaign',date:now-10*86400000},{score:2,pace:'classic',mode:'campaign',date:now-2*86400000},{score:3,pace:'classic',mode:'campaign',date:now}];assert.equal(s.filteredRecords({period:'week',now}).length,2);assert.equal(s.filteredRecords({period:'today',now}).length,1);});
test('legacy migration tolerates null and malformed rows and tags valid V1 scores',()=>{const raw=memory();raw.setItem('typing-maniac-library-v1',JSON.stringify({version:1,records:[null,{score:800,date:Date.now(),level:3,pace:'classic'}]}));const s=new LocalStore(raw);assert.equal(s.records.length,1);assert.equal(s.records[0].mode,'legacy');assert.equal(s.best(),0);});
test('wide words allocate glyph-aware card widths',()=>{assert.ok(wordCardWidth('WWWW')>wordCardWidth('IIII'));assert.ok(wordCardWidth('CLOCKWORK')>210);assert.ok(wordCardWidth('LIBRARY','ice')>wordCardWidth('LIBRARY'));});
test('spawned long cards remain wholly within the game field',()=>{const m=run({level:48});for(let i=0;i<150;i++){m.words=[];m.spawn();const w=m.words[0];assert.ok(w.x-w.width/2>=FIELD.left);assert.ok(w.x+w.width/2<=FIELD.right);}});
test('pause freezes cooldowns and resume does not erase partial input',()=>{const m=run();m.inventory.ice=1;m.setBuffer('STO');m.cast('ice');m.pause();const before=m.cooldowns.ice;advance(m,20);assert.equal(m.cooldowns.ice,before);m.resume();assert.equal(m.buffer,'STO');});

test('checkpoint cannot be imported into a different pace slot',()=>{const s=new LocalStore(memory()),m=run();clearStage(m);const cp=m.checkpoint();s.importData({version:2,checkpoints:{relaxed:cp}});assert.equal(s.checkpoint('relaxed'),null);});
